### ISSUE TITLE
Can't load playlist from remote server

### ISSUE THREAD

**Issue by FezVrasta** [Cigaras/IPTV.bundle#121]
I'm trying to load a playlist from this URL but it doesn't work:
> Provided playlist files are invalid, missing or empty, check the log file for more information

The URL is:
https://m3uparser-xkeguhsiok.now.sh/test.m3u

The log is:
```
2017-05-12 12:03:05,959 (7fffcae113c0) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 995f1de (Wed Apr 12 13:49:42 UTC 2017)
2017-05-12 12:03:05,959 (7fffcae113c0) :  DEBUG (core:361) - Using the standard policy
2017-05-12 12:03:05,959 (7fffcae113c0) :  DEBUG (core:450) - Starting runtime component.
2017-05-12 12:03:05,960 (7fffcae113c0) :  DEBUG (core:450) - Starting caching component.
2017-05-12 12:03:05,961 (7fffcae113c0) :  DEBUG (core:450) - Starting data component.
2017-05-12 12:03:05,961 (7fffcae113c0) :  DEBUG (core:450) - Starting networking component.
2017-05-12 12:03:05,961 (7fffcae113c0) :  DEBUG (networking:284) - Loaded HTTP cookies
2017-05-12 12:03:05,961 (7fffcae113c0) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2017-05-12 12:03:05,966 (7fffcae113c0) :  DEBUG (core:450) - Starting localization component.
2017-05-12 12:03:05,966 (7fffcae113c0) :  INFO (localization:409) - Setting the default locale to en-us
2017-05-12 12:03:05,966 (7fffcae113c0) :  DEBUG (localization:427) - Loaded en strings
2017-05-12 12:03:05,966 (7fffcae113c0) :  DEBUG (core:450) - Starting messaging component.
2017-05-12 12:03:05,967 (700011b80000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.iptv'
2017-05-12 12:03:05,968 (7fffcae113c0) :  DEBUG (core:450) - Starting debugging component.
2017-05-12 12:03:05,968 (7fffcae113c0) :  DEBUG (core:450) - Starting services component.
2017-05-12 12:03:05,968 (7fffcae113c0) :  DEBUG (core:450) - Starting myplex component.
2017-05-12 12:03:05,968 (7fffcae113c0) :  DEBUG (core:450) - Starting notifications component.
2017-05-12 12:03:06,068 (7fffcae113c0) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.iptv in namespace 'metadata'
2017-05-12 12:03:06,071 (7fffcae113c0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2017-05-12 12:03:06,085 (700011b80000) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2017-05-12 12:03:06,085 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2017-05-12 12:03:06,086 (700011b80000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2017-05-12 12:03:06,087 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2017-05-12 12:03:06,087 (700012386000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2017-05-12 12:03:06,087 (7fffcae113c0) :  DEBUG (core:150) - Finished starting framework core
2017-05-12 12:03:06,088 (7fffcae113c0) :  DEBUG (core:560) - Loading plug-in code
2017-05-12 12:03:06,167 (7fffcae113c0) :  DEBUG (core:566) - Finished loading plug-in code
2017-05-12 12:03:06,238 (700012386000) :  DEBUG (core:538) - Machine identifier is 38d2aa8c07fae50177d75363cc3ba158a7d45807
2017-05-12 12:03:06,239 (700012386000) :  DEBUG (core:539) - Server version is 1.5.5.3634-995f1dead
2017-05-12 12:03:06,272 (7fffcae113c0) :  DEBUG (runtime:640) - Adding a prefix handler for 'IPTV' ('/video/iptv')
2017-05-12 12:03:06,316 (700011b80000) :  DEBUG (services:362) - Loaded services
2017-05-12 12:03:06,320 (700011f83000) :  DEBUG (services:438) - No shared code to load
2017-05-12 12:03:06,320 (7fffcae113c0) :  DEBUG (preferences:258) - Loaded preferences from DefaultPrefs.json
2017-05-12 12:03:06,321 (7fffcae113c0) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.plugins.iptv
2017-05-12 12:03:06,322 (7fffcae113c0) :  INFO (datakit:93) - Loaded the dictionary file
2017-05-12 12:03:06,323 (7fffcae113c0) :  DEBUG (networking:166) - Requesting 'https://m3uparser-xkeguhsiok.now.sh/test.m3u'
2017-05-12 12:03:06,734 (7fffcae113c0) :  INFO (m3u_parser:105) - None
2017-05-12 12:03:06,734 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'PlaylistReloader'
2017-05-12 12:03:06,735 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'GuideReloader'
2017-05-12 12:03:06,735 (7fffcae113c0) :  INFO (core:611) - Started plug-in
2017-05-12 12:03:06,735 (7fffcae113c0) :  DEBUG (socketinterface:160) - Starting socket server
2017-05-12 12:03:06,736 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'start'
2017-05-12 12:03:06,736 (7fffcae113c0) :  INFO (socketinterface:184) - Socket server started on port 59072
2017-05-12 12:03:06,737 (7fffcae113c0) :  INFO (pipeinterface:25) - Entering run loop
2017-05-12 12:03:06,737 (7fffcae113c0) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2017-05-12 12:03:06,739 (7fffcae113c0) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2017-05-12 12:03:06,740 (7fffcae113c0) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 424 bytes
2017-05-12 12:03:06,750 (700012b8c000) :  DEBUG (runtime:717) - Handling request GET /video/iptv
2017-05-12 12:03:06,751 (700012b8c000) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-12 12:03:06,752 (700012b8c000) :  DEBUG (runtime:814) - Found route matching /video/iptv
2017-05-12 12:03:06,753 (700012b8c000) :  WARNING (runtime:1065) - Generating a callback path for a function with no route: <function LoadPlaylist at 0x108fc16e0>
2017-05-12 12:03:06,753 (700012b8c000) :  DEBUG (base:117) - Checking if com.plexapp.plugins.iptv is broken
2017-05-12 12:03:06,754 (700012b8c000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjQKY29tLnBsZXhhcHAucGx1Z2lucy5pcHR2czEwCmlkZW50aWZpZXJyMAo_'
2017-05-12 12:03:06,762 (700012b8c000) :  DEBUG (runtime:88) - Sending packed state data (105 bytes)
2017-05-12 12:03:06,762 (700012b8c000) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 1082 bytes
2017-05-12 12:03:06,777 (700012b8c000) :  DEBUG (runtime:717) - Handling request GET /video/iptv/:/function/LoadPlaylist?function_args=Y2VyZWFsMQoxCmRpY3QKMApyMAo_
2017-05-12 12:03:06,778 (700012b8c000) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-12 12:03:06,785 (700012b8c000) :  DEBUG (runtime:814) - Found route matching /video/iptv/:/function/LoadPlaylist
2017-05-12 12:03:06,786 (700012b8c000) :  DEBUG (runtime:125) - Calling function 'LoadPlaylist'
2017-05-12 12:03:06,786 (700012b8c000) :  DEBUG (networking:166) - Requesting 'https://m3uparser-xkeguhsiok.now.sh/test.m3u'
2017-05-12 12:03:07,203 (700012b8c000) :  INFO (m3u_parser:105) - None
2017-05-12 12:03:07,204 (700012b8c000) :  DEBUG (runtime:88) - Sending packed state data (105 bytes)
2017-05-12 12:03:07,204 (700012b8c000) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 437 bytes
2017-05-12 12:03:11,336 (700011b80000) :  INFO (datakit:131) - Saved the dictionary file
```

The playlist is provided by a small Express.js app, if I run it locally everything works fine, it doesn't work only when I run it from a remote server (now.sh).

Ideas?

**Comment by Cigaras** [comment]
I can not reproduce this. I opened Plex server web interface, navigated to the IPTV plug-in, openeded the preferences, replaced my playlist with `https://m3uparser-xkeguhsiok.now.sh/test.m3u`, clicked Save, then Reload playlist and got the Success message.

However I do not like warnings I see in the log so I committed a fix [5cefb59](https://github.com/Cigaras/IPTV.bundle/commit/5cefb59dde3d4ecf8f248d35ffb8387087dc3cb9), please download this non-release [version 2.1.1](https://github.com/Cigaras/IPTV.bundle/archive/master.zip) and check maybe it fixed Your issue.

**Comment by FezVrasta** [comment]
I downloaded the 2.1.1 bundle, renamed it to `IPTV.bundle` but it doesn't get detected by Plex.

**Comment by FezVrasta** [comment]
I still get the same error unfortunately. 

```
2017-05-15 13:52:57,658 (7fffcae113c0) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 995f1de (Wed Apr 12 13:49:42 UTC 2017)
2017-05-15 13:52:57,658 (7fffcae113c0) :  DEBUG (core:361) - Using the standard policy
2017-05-15 13:52:57,658 (7fffcae113c0) :  DEBUG (core:450) - Starting runtime component.
2017-05-15 13:52:57,660 (7fffcae113c0) :  DEBUG (core:450) - Starting caching component.
2017-05-15 13:52:57,660 (7fffcae113c0) :  DEBUG (core:450) - Starting data component.
2017-05-15 13:52:57,661 (7fffcae113c0) :  DEBUG (core:450) - Starting networking component.
2017-05-15 13:52:57,661 (7fffcae113c0) :  DEBUG (networking:284) - Loaded HTTP cookies
2017-05-15 13:52:57,661 (7fffcae113c0) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2017-05-15 13:52:57,667 (7fffcae113c0) :  DEBUG (core:450) - Starting localization component.
2017-05-15 13:52:57,667 (7fffcae113c0) :  INFO (localization:409) - Setting the default locale to en-us
2017-05-15 13:52:57,667 (7fffcae113c0) :  DEBUG (localization:427) - Loaded en strings
2017-05-15 13:52:57,667 (7fffcae113c0) :  DEBUG (core:450) - Starting messaging component.
2017-05-15 13:52:57,668 (7fffcae113c0) :  DEBUG (core:450) - Starting debugging component.
2017-05-15 13:52:57,668 (7fffcae113c0) :  DEBUG (core:450) - Starting services component.
2017-05-15 13:52:57,668 (700002981000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.plugins.iptv'
2017-05-15 13:52:57,669 (7fffcae113c0) :  DEBUG (core:450) - Starting myplex component.
2017-05-15 13:52:57,670 (7fffcae113c0) :  DEBUG (core:450) - Starting notifications component.
2017-05-15 13:52:57,783 (7fffcae113c0) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.plugins.iptv in namespace 'metadata'
2017-05-15 13:52:57,787 (7fffcae113c0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2017-05-15 13:52:57,814 (700002981000) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2017-05-15 13:52:57,815 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2017-05-15 13:52:57,816 (700002981000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2017-05-15 13:52:57,817 (700003187000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2017-05-15 13:52:57,817 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2017-05-15 13:52:57,818 (7fffcae113c0) :  DEBUG (core:150) - Finished starting framework core
2017-05-15 13:52:57,818 (7fffcae113c0) :  DEBUG (core:560) - Loading plug-in code
2017-05-15 13:52:57,827 (700003187000) :  DEBUG (core:538) - Machine identifier is 38d2aa8c07fae50177d75363cc3ba158a7d45807
2017-05-15 13:52:57,827 (700003187000) :  DEBUG (core:539) - Server version is 1.5.5.3634-995f1dead
2017-05-15 13:52:57,935 (700002981000) :  DEBUG (services:362) - Loaded services
2017-05-15 13:52:57,948 (700002d84000) :  DEBUG (services:438) - No shared code to load
2017-05-15 13:52:57,986 (7fffcae113c0) :  DEBUG (core:566) - Finished loading plug-in code
2017-05-15 13:52:58,068 (7fffcae113c0) :  DEBUG (runtime:640) - Adding a prefix handler for 'IPTV' ('/video/iptv')
2017-05-15 13:52:58,070 (7fffcae113c0) :  DEBUG (preferences:258) - Loaded preferences from DefaultPrefs.json
2017-05-15 13:52:58,071 (7fffcae113c0) :  DEBUG (preferences:178) - Loaded the user preferences for com.plexapp.plugins.iptv
2017-05-15 13:52:58,073 (7fffcae113c0) :  INFO (datakit:93) - Loaded the dictionary file
2017-05-15 13:52:58,073 (7fffcae113c0) :  DEBUG (networking:166) - Requesting 'https://m3uparser-xkeguhsiok.now.sh/test.m3u'
2017-05-15 13:52:58,488 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'PlaylistReloader'
2017-05-15 13:52:58,495 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'GuideReloader'
2017-05-15 13:52:58,495 (7fffcae113c0) :  INFO (core:611) - Started plug-in
2017-05-15 13:52:58,495 (7fffcae113c0) :  DEBUG (socketinterface:160) - Starting socket server
2017-05-15 13:52:58,498 (7fffcae113c0) :  DEBUG (runtime:1117) - Created a thread named 'start'
2017-05-15 13:52:58,498 (7fffcae113c0) :  INFO (socketinterface:184) - Socket server started on port 56594
2017-05-15 13:52:58,499 (7fffcae113c0) :  INFO (pipeinterface:25) - Entering run loop
2017-05-15 13:52:58,499 (7fffcae113c0) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2017-05-15 13:52:58,500 (7fffcae113c0) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2017-05-15 13:52:58,501 (7fffcae113c0) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 424 bytes
2017-05-15 13:52:58,511 (70000398d000) :  DEBUG (runtime:717) - Handling request GET /video/iptv
2017-05-15 13:52:58,512 (70000398d000) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-15 13:52:58,515 (70000398d000) :  DEBUG (runtime:814) - Found route matching /video/iptv
2017-05-15 13:52:58,516 (70000398d000) :  DEBUG (base:117) - Checking if com.plexapp.plugins.iptv is broken
2017-05-15 13:52:58,517 (70000398d000) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjQKY29tLnBsZXhhcHAucGx1Z2lucy5pcHR2czEwCmlkZW50aWZpZXJyMAo_'
2017-05-15 13:52:58,526 (70000398d000) :  DEBUG (runtime:88) - Sending packed state data (105 bytes)
2017-05-15 13:52:58,526 (70000398d000) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 1030 bytes
2017-05-15 13:52:58,539 (70000398d000) :  DEBUG (runtime:717) - Handling request GET /video/iptv/reloadplaylist
2017-05-15 13:52:58,540 (70000398d000) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2017-05-15 13:52:58,541 (70000398d000) :  DEBUG (runtime:814) - Found route matching /video/iptv/reloadplaylist
2017-05-15 13:52:58,542 (70000398d000) :  DEBUG (networking:166) - Requesting 'https://m3uparser-xkeguhsiok.now.sh/test.m3u'
2017-05-15 13:52:58,966 (70000398d000) :  DEBUG (runtime:88) - Sending packed state data (105 bytes)
2017-05-15 13:52:58,966 (70000398d000) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 437 bytes
2017-05-15 13:53:03,079 (700002981000) :  INFO (datakit:131) - Saved the dictionary file
```

I tried to host the same app on Heroku and on OpenShift and they both work, the only difference I'm aware of is that now.sh makes use of HTTP/2

**Comment by Cigaras** [comment]
If I look at the file https://m3uparser-xkeguhsiok.now.sh/test.m3u via browser it is a valid m3u file. Plex log shows no issues it it either, `Response: [200] MediaContainer, 437 bytes` indicates that request was successful, got 437 bytes of data in return, and it works for me with no issues, so there has to be something wrong with Your setup and I have no idea what to suggest You...

**Comment by FezVrasta** [comment]
If it helps, I'm on macOS 10.12.4. If any additional info can help diagnose the problem please let me know.
